// Generated by CoffeeScript 1.7.1
(function() {
  var OnlyOneTask, async, cluster, curlify, db, host, i, moment, nconf, orm, paging, password, printTask, restify, user, _i, _ref;

  cluster = require('cluster');

  orm = require('orm');

  moment = require('moment');

  nconf = require('./lib/nconf');

  restify = require('restify');

  curlify = require('request-as-curl');

  async = require('async');

  paging = require('./lib/paging');

  OnlyOneTask = require('./lib/OnlyOneTask');

  if (cluster.isMaster) {
    if (nconf.get('print:autoCheckPrint')) {
      printTask = OnlyOneTask.define('printTask', function(print) {
        if (print) {
          printTask.exec();
          return console.log(print.print_manage_id);
        }
      });
      printTask.crashTime = nconf.get('print:checkCrashTime') || 10000;
      setInterval(function() {
        return printTask.exec();
      }, 2000);
    }
    for (i = _i = 1, _ref = require('os').cpus().length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      cluster.fork();
    }
    cluster.on('exit', function(worker) {
      return cluster.fork();
    });
    return;
  }

  user = nconf.get('mysql:user');

  password = nconf.get('mysql:password');

  host = nconf.get('mysql:host');

  db = nconf.get('mysql:db');

  orm.connect("mysql://" + user + ":" + password + "@" + host + "/" + db, function(err, db) {
    var server, serverParams;
    if (err) {
      console.log('Cannot connect to Mysql.');
      throw err;
    }
    db.settings.set('connection.debug', true);
    serverParams = {};
    server = restify.createServer(serverParams);
    server.use(restify.gzipResponse());
    server.use(restify.authorizationParser());
    server.use(restify.bodyParser({
      mapParams: false
    }));
    server.use(restify.queryParser());
    server.use(function(req, res, next) {
      req.db = db;
      req.models = db.models;
      return next();
    });
    server.use(restify.CORS());
    server.use(restify.fullResponse());
    server.use(paging.supportPagination);
    server.on('uncaughtException', function(req, res, route, error) {
      console.log('Uncaught exception in ' + route.method + ' ' + route.path + ':');
      console.log(error);
      return res.send('server error.');
    });
    server.listen(nconf.get('server:port'), function() {
      return console.log("" + server.name + " listening at " + server.url);
    });
    require('./models/print_log')(db);
    require('./models/print_manage')(db);
    require('./routes/service.print')(server);
    OnlyOneTask.define('printTask', function(callback) {
      db.models.print_log.clearOld();
      db.models.print_log.checkTimeoutLogs();
      db.models.print_log.loopPrint();
      return db.models.print_manage.getOneEarlyChecked(function(err, print) {
        if (!print) {
          return callback();
        }
        return print.queryStatus(function(err, print) {
          if (print.print_staus === 0) {
            return callback(print);
          }
          return db.models.print_log.loopFill(print.print_manage_id, function() {
            return callback(print);
          });
        });
      });
    });
    return;
    return process.on('message', function(msg) {
      switch (msg) {
        case 'checkPrintTask':
          return db.models.print_log.loopPrint(null, function() {
            return process.send('checkingPrintLogListComplete');
          });
        case 'checkPrintStatus':
          db.models.print_log.clearOld();
          db.models.print_log.checkTimeoutLogs();
          db.models.print_log.loopPrint();
          return db.models.print_manage.getOneEarlyChecked(function(err, print) {
            if (!print) {
              return process.send('checkingPrintListComplete');
            }
            return print.queryStatus(function(err, print) {
              if (print.print_status === 0) {
                return process.send('checkingPrintListComplete');
              } else {
                return db.models.print_log.loopFill(print.print_manage_id, function() {
                  return process.send('checkingPrintListComplete');
                });
              }
            });
          });
      }
    });
  });

}).call(this);
