// Generated by CoffeeScript 1.7.1
(function() {
  var Pos, moment;

  Pos = require('../lib/pos');

  moment = require('moment');

  module.exports = function(server) {
    server.get('/service/print/till/:ip', function(req, res, next) {
      res.send({
        status: Pos.kickOutDrawer(req.params.ip) === true ? 1 : -1
      });
      return next();
    });
    server.get('/service/print/notice', function(req, res, next) {
      process.send('checkPrintTask');
      res.send({
        status: 1
      });
      return next();
    });
    server.get('/service/print/query/:ip', function(req, res, next) {
      res.send({
        status: Pos.query(req.params.ip)
      });
      return next();
    });
    return server.get('/service/print/notice1', function(req, res, next) {
      var a;
      a = 1;
      return console.log(a.test.op);
    });
  };

}).call(this);
