// Generated by CoffeeScript 1.7.1
(function() {
  var fs, logFileName, logFolder, moment, path;

  moment = require('moment');

  fs = require('fs');

  path = require('path');

  logFolder = '../logs/';

  logFileName = '_error.txt';

  module.exports = function(msg, callback) {
    var logPath;
    if (callback == null) {
      callback = function() {};
    }
    logPath = path.join(__dirname, logFolder + moment(new Date()).format('YYYY-MM-DD') + logFileName);
    return fs.appendFile(logPath, moment(new Date()).format('YYYY-MM-DD HH:mm:ss SSS') + ' ' + msg + '\r\n', callback);
  };

}).call(this);
