// Generated by CoffeeScript 1.7.1
(function() {
  var fs, logFileName, logFolder, moment;

  moment = require('moment');

  fs = require('fs');

  logFolder = '../logs/';

  logFileName = '_error.txt';

  module.exports = function(msg, callback) {
    var path;
    if (callback == null) {
      callback = function() {};
    }
    path = logFolder + moment(new Date()).format('YYYY-MM-DD') + logFileName;
    console.log(path, 123123123123123);
    return fs.appendFile(path, moment(new Date()).format('YYYYMMDDHHmmssZ') + ' ' + msg + '\r\n', callback);
  };

}).call(this);
