// Generated by CoffeeScript 1.7.1
(function() {
  var nconf, path;

  path = require('path');

  nconf = module.exports = require('nconf');

  nconf.file({
    'file': path.join(__dirname, '../config.json')
  });

  nconf.defaults({
    'mysql': {
      'host': 'localhost',
      'user': 'root',
      'password': 'sa',
      'db': 'daofulin_sell',
      'charset': 'utf8'
    },
    'server': {
      'port': 8080,
      'hostName': 'api.a.com'
    },
    'print': {
      'autoCheckPrint': true,
      'checkTimes': 1000 * 60,
      'checkCrashTime': 1000 * 60 * 2,
      'autoPrintErrorLogs': true,
      'clearOldTimes': 1000 * 3600 * 24 * 2,
      'printTimeout': 1000 * 10
    }
  });

}).call(this);
