// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    supportPagination: function(req, res, next) {
      req.limit = req.query !== null && req.query.limit !== null && !isNaN(req.query.limit) ? Number(req.query.limit) : 20;
      req.skip = req.query !== null && req.query.skip !== null && !isNaN(req.query.skip) ? Number(req.query.skip) : 0;
      return next();
    }
  };

}).call(this);
