// Generated by CoffeeScript 1.7.1
(function() {
  var CONST, Pos, async, cluster, moment, nconf, orm;

  Pos = require('../lib/pos');

  nconf = require('../lib/nconf');

  orm = require('orm');

  moment = require('moment');

  cluster = require('cluster');

  async = require('async');

  CONST = {
    waiting: 0,
    success: 1,
    fail: 2,
    error: 3,
    printing: 4,
    other: 5
  };

  module.exports = function(db) {
    var print_log;
    print_log = db.define('print_log', {
      print_log_id: {
        type: 'serial'
      },
      addtime: {
        type: 'integer',
        size: 11
      },
      printIP: {
        type: 'text'
      },
      print_message: {
        type: 'object'
      },
      is_ok: {
        type: 'integer'
      },
      success_no: {
        type: 'text'
      },
      print_type: {
        type: 'text'
      },
      print_time: {
        type: 'integer',
        size: 11
      },
      trans_id: {
        type: 'text'
      },
      print_nums: {
        type: 'integer',
        size: 11
      },
      print_sort: {
        type: 'integer'
      }
    }, {
      id: 'print_log_id',
      methods: {
        print: function(callback) {
          var initStatus;
          if (callback == null) {
            callback = function() {};
          }
          initStatus = this.is_ok;
          this.is_ok = this.printIP ? CONST.printing : CONST.other;
          this.print_time = new Date().getTime() / 1000;
          this.trans_id = null;
          return this.save((function(_this) {
            return function(err) {
              var beforeStauts, result;
              if (err || !_this.printIP) {
                return callback(_this);
              }
              result = Pos.print(_this.printIP, _this.print_message);
              beforeStauts = _this.is_ok;
              _this.is_ok = result === 0 ? CONST.success : CONST.fail;
              if (result === 'OpenError') {
                _this.is_ok = CONST.error;
              }
              _this.print_nums++;
              console.log(moment(new Date()).format('HH:mm:ss SSS'), '进程,日志', cluster.worker.id, _this.print_log_id, initStatus, beforeStauts, _this.is_ok, result, _this.print_nums);
              return _this.save(function(err) {
                return callback(_this);
              });
            };
          })(this));
        }
      }
    });
    print_log.getOneByStatus = function(status, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.one({
        is_ok: status
      }, callback);
    };
    print_log.getOneByPrintManage = function(print_manage_id, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.one({
        print_id: print_manage_id
      }, callback);
    };
    print_log.loopFill = function(print_manage_id, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.find({
        print_id: print_manage_id,
        is_ok: CONST.error
      }).each(function(print_log) {
        return print_log.is_ok = CONST.waiting;
      }).save((function(_this) {
        return function(err) {
          return _this.loopPrint(null, callback);
        };
      })(this));
    };
    print_log.loopPrint = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.find({
        is_ok: CONST.waiting
      }).limit(1).order('print_sort').run(function(err, list) {
        if (err || !list || list.length === 0) {
          return callback();
        }
        return list[0].print(callback);
      });
    };
    print_log.clearOld = function(callback) {
      var clearTimes, lastTime;
      if (callback == null) {
        callback = function() {};
      }
      clearTimes = nconf.get('print:clearOldTimes');
      if (clearTimes === 0) {
        return callback();
      }
      lastTime = (new Date().getTime() - clearTimes) / 1000;
      return this.find({
        addtime: orm.lt(lastTime)
      }).remove(callback);
    };
    return print_log.checkTimeoutLogs = function(callback) {
      var lastTime, timeOut;
      if (callback == null) {
        callback = function() {};
      }
      timeOut = nconf.get('print:printTimeout');
      if (timeOut === 0) {
        return callback();
      }
      lastTime = (new Date().getTime() - timeOut) / 1000;
      return this.find({
        print_time: orm.lt(lastTime),
        is_ok: CONST.printing
      }).each(function(log) {
        return log.is_ok = CONST.waiting;
      }).save(callback);
    };
  };

}).call(this);

//# sourceMappingURL=print_log.js.map